containers:
  - name: forum-container
    image: marammanai/forum-service:latest
    ports:
      - containerPort: 8085
    volumeMounts:
      - name: cephfs-vol
        mountPath: /mnt/cephfs/forum

volumes:
  - name: cephfs-vol
    persistentVolumeClaim:
      claimName: cephfs-pvc
