server.port=8088
spring.application.name=forum-service

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-service.default.svc.cluster.local:8761/eureka}

# Logging
logging.level.org.springframework=INFO
logging.level.tn.esprit.forumservice=DEBUG

# Chemin de montage CephFS
cephfs.mount.path=/mnt/cephfs
